---

- name: Install strongswan
  apt:
    name: "{{ strongswan_package }}"
    state: present

- name: Enable strongswan
  service:
    name: "{{ strongswan_service }}"
    enabled: yes

- name: Install strongswan_extra_packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ strongswan_extra_packages }}"
  notify: Restart strongswan
